### ISSUE TITLE
Issue in Password generator project

### ISSUE THREAD

**Issue by SURAJSHARMA-ind** [hiteshchoudhary/chai-aur-react#108]
In pass generator project when u click on number checkbox  their is a chance where u didn't get any number in your password because their is low probability  of number  they are  just 0-9 . 
![Passgen_Issue](https://github.com/hiteshchoudhary/chai-aur-react/assets/80053118/065856bb-098d-46f5-806b-04eda2d532f0)

**Comment by akrathor18** [comment]
Ok, thanks @SURAJSHARMA-ind  for informing about this small bug. I will try to resolve this bug

**Comment by Milan13-cmd** [comment]
replace this code    
 if (numberAlllowd) {str += "0123456789";
With this new code so that bug can be remove
if (numberAlllowd) {
    // Ensure at least one number in the password
    pass += Math.floor(Math.random() * 10); // Append a random number (0-9)
    str += "0123456789";  }
