### ISSUE TITLE
Currency Conertor api not working

### ISSUE THREAD

**Issue by imshubham07** [hiteshchoudhary/chai-aur-react#121]
## let url = `https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/${currency}.json`

**Comment by Codewithsandi** [comment]
https://latest.currency-api.pages.dev/v1/currencies/${currency}.json
or
https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies/${currency}.json

Github Link: https://github.com/fawazahmed0/exchange-api

**Comment by sunriseateast** [comment]
You can use also

https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies/eur.json

**Comment by imshubham07** [comment]
done
