### ISSUE TITLE
Getting error in 'getcurrentUser' function  in "12MegaBlog" Project.

### ISSUE THREAD

**Issue by 25shivansh** [hiteshchoudhary/chai-aur-react#170]
Whenever i am starting my project it shows following errors . PLEASE HELP ME WITH THIS 
![Screenshot 2024-08-05 005317](https://github.com/user-attachments/assets/04ea85d7-f959-4af7-8971-863f43ad0c7b)

**Comment by thearyansingh** [comment]
same problem 
how you solved??

**Comment by thearyansingh** [comment]
![Uploading Screenshot 2024-08-07 134041.png…]()

**Comment by divanshurawat** [comment]
Same problem in auth.js , if anyone able to solve that?

**Comment by 25shivansh** [comment]
this problem is still not solved, if anyone knows how to do it please tell me.

**Comment by ROKUMATE** [comment]
Refer issue #161 if it could help u 
Thats only what i found

**Comment by hmaadtaarek** [comment]
still not solved the issue by issue #161

**Comment by 25shivansh** [comment]
ISSUE RESOLVED !  just go to the file app.jsx file and  return <Header/> <Outlet/> <Footer/>. This will finally resolve login/ signup error.

**Comment by divanshurawat** [comment]
@25shivansh return what?

**Comment by 25shivansh** [comment]
return !loading ?(
    header,outlet,and footer
![Screenshot 2024-10-24 094835](https://github.com/user-attachments/assets/44b7d2fa-f5ff-4404-98a9-5f5acf89b33a)

**Comment by 25shivansh** [comment]
tell me whether it is working or not

**Comment by yash291** [comment]
its working after adding Outlet

**Comment by AbhishekSinghaniya2002** [comment]
> Whenever i am starting my project it shows following errors . PLEASE HELP ME WITH THIS ![Screenshot 2024-08-05 005317](https://private-user-images.githubusercontent.com/160400936/354929259-04ea85d7-f959-4af7-8971-863f43ad0c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNjIwODksIm5iZiI6MTczNTA2MTc4OSwicGF0aCI6Ii8xNjA0MDA5MzYvMzU0OTI5MjU5LTA0ZWE4NWQ3LWY5NTktNGFmNy04OTcxLTg2M2Y0M2FkMGM3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNzM2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGQ3YjUyOTFkMTZjNTcxODVmNTZmMGY0NzQxZWY0NGUwOGM4OWNkYjY0YmEwN2JmYzkxOWU0OWFlODk0NjU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tASWHzUtFWX7X9eTkF7iqXcvpJ513oemCBQyhOv9GEI)

bro i am facing same problem have you solved all errors

**Comment by AbhishekSinghaniya2002** [comment]
> tell me whether it is working or not

@25shivansh  bro i have done all this but i am facing same error

**Comment by 25shivansh** [comment]
tell me all the errors that you are facing .

**Comment by AbhishekSinghaniya2002** [comment]
@25shivansh 
bro   auth.js me broblem aa raha hai  har baar yehi de raha hai . apprite
ke vajah se issue hai lagta hai lekin mai resolve nahi kar pa raha hu ye jo
apprite ka url hai na lagta hai ussi me dikkat hai maine try kiya apprite
se jo vaha link hai vahi maine rakha hai jaise sir ne kiya hai . sir ke
code se mila liya code bhi sahi hai sare . maine tumhare file se bhi milaya
hi even apna comment karke tumhri code bhi puri copy paste ki file bhi
rename kiya lekin error nahi resolve ho raha hai . mai thoda new hu isme
isliye mujhe jayada nahi samajh aa rah hai . tum apna whatshap number de
sakte ho kya . ye hi error aa raha aap try kake dekho bhai
https://cloud.appwrite.io/v1/account 401 (Unauthorized)

**Comment by AbhishekSinghaniya2002** [comment]
@25shivansh 
![Screenshot (3310)](https://github.com/user-attachments/assets/7b28897b-6852-4755-acbe-5df97026486e)

**Comment by raipranjal-2909** [comment]
I also facing the same problem and I have tried everything but can not able to fix it.

![Image](https://github.com/user-attachments/assets/e4364557-c467-4238-a721-436e64e700dc)

**Comment by 1nameAli** [comment]
same error
i am facing

**Comment by FutureTL** [comment]
adding outlet solved it. Thanks @25shivansh

**Comment by FutureTL** [comment]
was anyone able to solve it?
