### ISSUE TITLE
Bug in Password Generator

### ISSUE THREAD

**Issue by geeky01adarsh** [hiteshchoudhary/chai-aur-react#41]
Hey @hiteshchoudhary, 
I was going through the algorithm you used for the password generator project and found a minor bug there. 

Even after I select numbers or characters, there is still a possibility that the password won't contain them as random indexes could be from the front only, even not the capital and small letters at the same time.

![image](https://github.com/hiteshchoudhary/chai-aur-react/assets/74068552/524fddbe-e38e-4bfb-a180-0f583c018cd4)

It could be fixed using a validation. Should I try to fix that?

**Comment by VARUN-KUSH** [comment]
yeah sure i would love to see the solution

**Comment by geeky01adarsh** [comment]
> yeah sure i would love to see the solution

Sure @VARUN-KUSH I will create a PR for it.

**Comment by bkvats** [comment]
Created a pull request for this after fixing the algo: You can have a look Fix: #95
